# Generated by Django 3.2.5 on 2022-07-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_auto_20220709_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lname',
            new_name='last_name',
        ),
    ]
